config/routes.rb
Rails.application.routes.draw do

  root 'kittens#index'

resources :kittens

end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json {render json: @kittens}
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Successfully saved"
      redirect_to @kitten
    else
      flash[:error] = "Problem saving this entry!"
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json {render json: @kitten}
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    @kitten.update_attributes(kitten_params)
    if @kitten.save
      flash[:success] = "Successfully updated"
      redirect_to @kitten
    else
      flash[:error] = "Update failed!"
    end
  end

  def destroy
    kitten = Kitten.find(params[:id])
    kitten.destroy
    flash[:success] = "Successfully deleted!"
    redirect_to root_url
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten.html.erb
<%= form_for @kitten do |f| %>

<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :age %>
  <%= f.text_field :age %>
</p>

<p>
  <%= f.label :softness %>
  <%= f.text_field :softness %>
</p>

<p>
  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %>
</p>

<p><%= f.submit %></p>

<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten's Profile</h1>

<%= render @kitten %>

app/views/kittens/index.html.erb
<h1>Index page</h1>

<p><%= link_to "Add new Kitten", new_kitten_path %></p>

<% if @kittens.any? %>
  <% @kittens.each do |kitten| %>
    <h2><%= link_to kitten.name, kitten_path(kitten) %></h2>
    <p><%= kitten.age %></p>
    <p><%= kitten.cuteness %></p>
    <p><%= kitten.softness %></p>
  <% end %>
<% else %>
  <strong>There are no kittens!</strong>
<% end %>

app/views/kittens/new.html.erb
<h1>Register New Kitten</h1>

<%= render @kitten %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %>'s Profile</h1>

  <p><%= @kitten.age %></p>
  <p><%= @kitten.cuteness %></p>
  <p><%= @kitten.softness %></p>

  <p>
    <%= link_to "Edit", edit_kitten_path(@kitten) %>
    <%= link_to "Destroy", kitten_path(@kitten), method: "delete" %>

  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |message_type, message| %>
  <%= message %>
<% end %>

<%= yield %>

</body>
</html>